sudo: false

language: python

python:
  - 3.6

env:
  - Flask=1.0.2

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - python manage.py test

after_success:
  - codecov